seed: 777 # random seed
data_path: ./ # input data path
batch_size: 400 # train batch size
eval_batch_size: 400 # evaluation batch size
num_workers: 10 # number of subprocesses to use for data loading
max_epochs: 24 # number of maximum epochs
use_amp: false # use AMP (Automatic Mixed Precision)
weight_decay: 1e-4
debug: false
train_epoch_length: null
eval_epoch_length: null
filename_prefix: training
n_saved: 2
save_every_iters: 1000
patience: 10
output_dir: ./logs
log_every_iters: 10
lr: 1e-2 # learning rate
model: resnet18 # model name