version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  tests:
    docker:
      - image: cimg/python:3.7.11-node

    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: google-chrome --version
      - run: chromedriver --version
      - run: node --version
      - run: python --version

workflows:
  run_tests:
    jobs:
      - tests
