version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3
  node: circleci/node@4.5.2

commands:
  install_dependencies:
    steps:
      - run: sudo ln -sfn `which python3` `which python`

      - node/install:
          lts: true

      - node/install-packages:
          override-ci-command: npm i -g pnpm

      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - run:
          name: Check Setup
          command: |
            python --version
            node --version
            npm --version
            pnpm --version
            google-chrome --version
            chromedriver --version

      - run:
          name: Install Dependencies
          command: |
            pip install wheel setuptools pip -Uqq
            pip install -r ./scripts/requirements.txt -f https://download.pytorch.org/whl/cpu/torch_stable.html --progress-bar off
            pip uninstall -y tqdm -q
            pnpm i --frozen-lockfile --color

      - run:
          name: Download Datasets
          command: |
            python ./scripts/download_datasets.py
            pip install tqdm

      - run:
          name: Build, Test, Unzip
          command: |
            pnpm build
            pnpm test:ci
            sh ./scripts/run_tests.sh unzip

  run_tests:
    parameters:
      kind:
        default: 'simple'
        type: string
    steps:
      - run:
          name: Run tests << parameters.kind >>
          no_output_timeout: 30m
          command: |
            sh ./scripts/run_tests.sh << parameters.kind >>

jobs:
  tests_simple_all:
    machine:
      image: ubuntu-2004:202107-01
    steps:
      - checkout
      - install_dependencies
      - run_tests:
          kind: 'simple'
      - run_tests:
          kind: 'all'

#   tests_all:
#     docker:
#       - image: cimg/python:3.6.14-node
#     steps:
#       - checkout
#       - install_dependencies
#       - run_tests:
#           kind: 'all'

  tests_launch:
    machine:
      image: ubuntu-2004:202107-01 
    steps:
      - checkout
      - install_dependencies
      - run_tests:
          kind: 'launch'

  tests_spawn:
    machine:
      image: ubuntu-2004:202107-01
    steps:
      - checkout
      - install_dependencies
      - run_tests:
          kind: 'spawn'

workflows:
  tests:
    jobs:
#       - tests_simple_all
      - tests_launch
      - tests_spawn
