#::= from_template_common ::#
model: bert-base-uncased
model_dir: /tmp/model
tokenizer_dir: /tmp/tokenizer
num_classes: 1
drop_out: .3
n_fc: 768
weight_decay: 0.01
num_warmup_epochs: 0
max_length: 256
lr: 0.00005
