#::= from_template_common ::#
model: bert-base-uncased # model for text classification
model_dir: /tmp/model # path of model directory  
tokenizer_dir: /tmp/tokenizer # path of directory containing tokenizer
num_classes: 1 # number of classes
drop_out: .3 # drop out rate
n_fc: 768 # number of fully-connected layers
weight_decay: 0.01 # parameter for weight decay, default, 1e-4.
num_warmup_epochs: 0 # number of warm-up epochs before learning rate decay
max_length: 256 # maximum length of texts
lr: 0.00005
