seed: 666
render: true
gamma: 0.975
recordings_path: ./recordings
lr: 0.001
max_episodes: 500
log_every_episodes: 1
save_every_episodes: 10
output_dir: ./logs
epsilon: 1.0
epsilon_min: 0.01
epsilon_decay: 0.9999
batch_size: 512
steps_per_episode: 1500